server:
  port: 8080

spring:
  application:
    name: security-saml2-login

  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              metadata-uri: https://dev-22549583.okta.com/app/exkd3rl5a5kPyTfg55d7/sso/saml/metadata
            signing:
              credentials:
                - private-key-location: classpath:local.key
                  certificate-location: classpath:local.crt
            singlelogout:
              binding: POST
              response-url: "{baseUrl}/logout/saml2/slo"
          azure:
            assertingparty:
              metadata-uri: xxxxxx
            singlesignon:
              url: xxxxxx

logging:
  level:
    org.springframework.security: DEBUG