server:
  port: 8080

spring:
  application:
    name: security-saml2-login

  security:
    saml2:
      relyingparty:
        registration:
          okta:
            assertingparty:
              entity-id: http://www.okta.com/exkd35z6y0lZIaVwn5d7
              metadata-uri: https://dev-22549583.okta.com/app/exkd35z6y0lZIaVwn5d7/sso/saml/metadata
              verification:
                credentials:
                  - certificate-location: "classpath:okta.cert"
              singlesignon:
                url: https://dev-22549583.okta.com/app/dev-22549583_chtlabstest02_1/exkd35z6y0lZIaVwn5d7/sso/saml
                sign-request: false
logging:
  level:
    org.springframework.security: DEBUG