### 获取用户
GET http://127.0.0.1:8080/user/1
Authorization: eyJhbGciOiJSUzI1NiJ9.eyJkYXRhIjoie1wiaWRcIjoxLFwidXNlck5hbWVcIjpcIiQyYSQxMCRGR3c5WXg3S3JzNzdIV0oyclpRZVAuQk1IZDhTcHFsZXk4UzNvQ3VReHo5MUUvT2NwTkYzR1wiLFwicm9sZXNcIjpbXCJBRE1JTlwiXX0iLCJqdGkiOiIzNGIwNTAxMy0zMjdjLTRjNjQtODQyYS1mODhhOTE1OTA5MzgiLCJleHAiOjE2OTg5MjE0OTR9.UGo2uwY8WupkP6UeSwTxZu0mgXb5YlsRfVVeuWYmA3Nw9isZHemo_LLSK4YcqCNL7_JdYivpDhB9RW_d8fE_dFX88HN19sJbbQb2a5U_kYzMxw4OYRZtcwFDPTNfCFt3QbOgO58NgEADVYRjE0mtJo3weipd5aMhvssyNLQgdHc

